# Generated by Django 5.2.16 on 2026-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee'), ('IT Manager', 'IT Manager'), ('Finance Admin', 'Finance Admin'), ('Department Head', 'Department Head'), ('Recruiter', 'Recruiter')], default='HR', max_length=20),
        ),
    ]
