# Generated by Django 5.2.16 on 2026-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_department_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hq_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
