# Generated by Django 5.2.16 on 2026-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_hq_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee'), ('IT Manager', 'IT Manager'), ('Finance Admin', 'Finance Admin'), ('Department Head', 'Department Head'), ('Recruiter', 'Recruiter'), ('Auditor', 'Auditor'), ('Contractor', 'Contractor')], default='HR', max_length=20),
        ),
    ]
