# Generated by Django 5.2.16 on 2026-07-18 19:51

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Trusted by agency recruiters across 100+ countries!', max_length=120)),
                ('hero_heading_pre', models.CharField(default='The recruitment CRM built for', max_length=120)),
                ('hero_heading_highlight', models.CharField(default='closing placements', max_length=60)),
                ('hero_heading_post', models.CharField(default=', not chasing spreadsheets.', max_length=120)),
                ('hero_subtitle', models.TextField(default='EvoHR brings your candidates, clients, and open requisitions into one system of record — so your desk runs on data, not memory.')),
                ('hero_cta_primary_label', models.CharField(default='Book a Demo', max_length=40)),
                ('hero_cta_secondary_label', models.CharField(default='Start a 30 Day Trial', max_length=40)),
                ('hero_note', models.CharField(default='No credit card required · Cancel anytime', max_length=120)),
                ('dashboard_total_placements', models.IntegerField(default=31)),
                ('dashboard_growth_label', models.CharField(default='+18% QoQ', max_length=20)),
                ('dashboard_placements', wagtail.fields.StreamField([('point', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Feb', 'max_length': 10}), 1: ('wagtail.blocks.IntegerBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('month', 0), ('value', 1)]], {})})),
                ('dashboard_notifications', wagtail.fields.StreamField([('notification', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 3}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary / success (emerald)'), ('amber', 'Amber / warning'), ('maroon', 'Maroon / danger'), ('neutral', 'Neutral / grey')]}), 5: ('wagtail.blocks.StructBlock', [[('initials', 0), ('name', 1), ('role', 2), ('status', 3), ('tone', 4)]], {})})),
                ('dashboard_payroll_label', models.CharField(default='Payroll · Aug run', max_length=40)),
                ('dashboard_payroll_amount', models.CharField(default='$186,400', max_length=20)),
                ('dashboard_payroll_subtext', models.CharField(default='42 contractors · processed', max_length=60)),
                ('dashboard_payroll_status', models.CharField(default='Reconciled', max_length=30)),
                ('dashboard_attendance_percent', models.IntegerField(default=93)),
                ('dashboard_attendance_subtext', models.CharField(default='42 / 45 timesheets submitted', max_length=60)),
                ('trust_logos', wagtail.fields.StreamField([('logo', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60})})),
                ('suite_eyebrow', models.CharField(default='The EvoHR suite', max_length=60)),
                ('suite_title', models.CharField(default='One platform, every part of the desk.', max_length=160)),
                ('suite_subtitle', models.TextField(default='Start with the core CRM, then turn on the modules your agency actually needs.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='PRICING', max_length=60)),
                ('heading', models.CharField(default='Priced per recruiter, not per headache.', max_length=160)),
                ('subtitle', models.TextField(default='Every plan includes the core CRM and ATS. Add payroll, benefits, and mobility as your desk grows.')),
                ('tiers', wagtail.fields.StreamField([('tier', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': "Tick for a 'Custom / talk to sales' tier with no price", 'required': False}), 3: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Effective monthly price when billed annually', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'help_text': "Highlight as 'Most popular'", 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Start free trial', 'max_length': 40}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('is_custom', 2), ('monthly_price', 3), ('annual_price', 4), ('featured', 5), ('cta_label', 6), ('features', 8)]], {})})),
                ('comparison_rows', wagtail.fields.StreamField([('row', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('yes', 'Included'), ('partial', 'Partial'), ('no', 'Not included')]}), 2: ('wagtail.blocks.StructBlock', [[('feature', 0), ('starter', 1), ('growth', 1), ('enterprise', 1)]], {})})),
                ('faq_items', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('tag', models.CharField(help_text='e.g. CORE, PAYROLL, TECH STAFFING', max_length=40)),
                ('name', models.CharField(help_text='e.g. EvoHR Payroll', max_length=60)),
                ('short_description', models.TextField(help_text='Shown on the homepage suite cards')),
                ('long_description', models.TextField(blank=True, help_text='Shown on the Solutions page')),
                ('bullets', wagtail.fields.StreamField([('bullet', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 140})}, help_text='Shown as a checklist on the Solutions page')),
                ('widget_type', models.CharField(choices=[('none', 'No widget'), ('pipeline', 'Pipeline stage counts'), ('payroll', 'Payroll runs list'), ('it', 'Skill match bars'), ('benefits', 'Benefits list'), ('hire', 'Requisitions list'), ('mobility', 'Mobility list'), ('deals', 'Deals pipeline list')], default='none', max_length=20)),
                ('widget_rows', wagtail.fields.StreamField([('row', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary / success (emerald)'), ('amber', 'Amber / warning'), ('maroon', 'Maroon / danger'), ('neutral', 'Neutral / grey')]}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('status', 1), ('tone', 2)]], {})})),
                ('widget_stages', wagtail.fields.StreamField([('stage', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.IntegerBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('count', 1)]], {})})),
                ('widget_skills', wagtail.fields.StreamField([('skill', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.IntegerBlock', (), {'max_value': 100, 'min_value': 0}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('percent', 1)]], {})})),
            ],
            options={
                'ordering': ['sort_order'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='RESOURCES', max_length=60)),
                ('heading', models.CharField(default='Guides, playbooks, and help — all in one place.', max_length=160)),
                ('subtitle', models.TextField(default='Everything to get your desk running on EvoHR, and keep it running well.')),
                ('blog_posts', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Jul 12 · 6 min read' or '12.4k views'", 'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('meta', 1)]], {})})),
                ('guides', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Jul 12 · 6 min read' or '12.4k views'", 'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('meta', 1)]], {})})),
                ('help_articles', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Jul 12 · 6 min read' or '12.4k views'", 'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('meta', 1)]], {})})),
                ('api_docs_title', models.CharField(default='Build on the EvoHR API', max_length=100)),
                ('api_docs_description', models.CharField(default='REST endpoints for candidates, requisitions, placements, and payroll.', max_length=200)),
                ('api_docs_snippet', models.TextField(default='GET /v1/candidates/{id}\n{\n  "name": "Ava Thompson",\n  "stage": "interview",\n  "role": "Backend Engineer"\n}')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SolutionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='SOLUTIONS', max_length=60)),
                ('heading', models.CharField(default='Everything your desk needs, connected.', max_length=160)),
                ('subtitle', models.TextField(default='Start with the core CRM, then turn on the modules your agency actually needs — each one shares the same candidate and client record.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UseCasesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='USE CASES', max_length=60)),
                ('heading', models.CharField(default='Built for how your desk actually works.', max_length=160)),
                ('subtitle', models.TextField(default='Four ways recruiting teams run their business on EvoHR — pick the shape that matches yours.')),
                ('cases', wagtail.fields.StreamField([('case', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. STAFFING AGENCIES', 'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 3.2x', 'max_length': 20}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. faster time-to-fill', 'max_length': 60}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('tag', 0), ('title', 1), ('description', 2), ('stat', 3), ('stat_label', 4), ('bullets', 6)]], {})})),
                ('shift_eyebrow', models.CharField(default='The shift', max_length=60)),
                ('shift_title', models.CharField(default='What changes the week you switch on.', max_length=160)),
                ('before_items', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 140})})),
                ('after_items', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 140})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WhoWeServePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='WHO WE SERVE', max_length=60)),
                ('heading', models.CharField(default='One system, every seat on the team.', max_length=160)),
                ('subtitle', models.TextField(default='Recruiters, ops, sales, and finance all work off the same record — just shaped around what each role actually needs.')),
                ('roles', wagtail.fields.StreamField([('role', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. AGENCY RECRUITERS', 'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No widget'), ('pipeline', 'Pipeline stage counts'), ('payroll', 'Payroll runs list'), ('it', 'Skill match bars'), ('benefits', 'Benefits list'), ('hire', 'Requisitions list'), ('mobility', 'Mobility list'), ('deals', 'Deals pipeline list')], 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary / success (emerald)'), ('amber', 'Amber / warning'), ('maroon', 'Maroon / danger'), ('neutral', 'Neutral / grey')]}), 9: ('wagtail.blocks.StructBlock', [[('label', 6), ('status', 7), ('tone', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('label', 7), ('count', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'max_value': 100, 'min_value': 0}), 15: ('wagtail.blocks.StructBlock', [[('label', 7), ('percent', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('tag', 0), ('title', 1), ('description', 2), ('bullets', 4), ('widget_type', 5), ('widget_rows', 10), ('widget_stages', 13), ('widget_skills', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_tagline', models.CharField(default='The recruitment CRM for agencies that place people for a living.', max_length=200)),
                ('copyright_holder', models.CharField(default='EvoHR, Inc. All rights reserved.', max_length=120)),
                ('footer_columns', wagtail.fields.StreamField([('column', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 1), ('links', 3)]], {})})),
                ('cta_default_title', models.CharField(default='Put your desk on the record.', max_length=120)),
                ('cta_default_subtitle', models.CharField(default='Start a free 30-day trial. No credit card, no setup calls required.', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
