# Generated by Django 5.2.16 on 2026-07-19 19:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='stats_cta_label',
            field=models.CharField(default='Book a demo', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_heading',
            field=models.CharField(default='Pulse makes closing placements effortless', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_items',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 150+, $20B+, 94%', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. countries, client retention', 'max_length': 60}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {})}),
        ),
    ]
