# Generated by Django 5.2.16 on 2026-07-19 20:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepage_stats_cta_label_homepage_stats_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Keep it specific and outcome-based', 'max_length': 280}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Founder, Bright Path Staffing', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 3}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('name', 1), ('title', 2), ('initials', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_eyebrow',
            field=models.CharField(default='What agencies say', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(default='Recruiters run their whole desk on this.', max_length=160),
        ),
    ]
