# Generated by Django 5.2.16 on 2026-07-20 23:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homepage_testimonials_homepage_testimonials_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='trust_logos',
            field=wagtail.fields.StreamField([('logo', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Company name, used as image alt text', 'max_length': 60}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Direct URL to the logo image (SVG or PNG)'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo_url', 1)]], {})}),
        ),
    ]
