# Generated by Django 5.2.16 on 2026-07-20 23:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_homepage_trust_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='trust_logos',
            field=wagtail.fields.StreamField([('logo', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Company name, used as image alt text', 'max_length': 60}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Direct URL to the logo image (SVG or PNG) — use this OR upload below', 'required': False}), 2: ('cms.blocks.Base64ImageBlock', (), {'help_text': 'Or upload a logo image directly (stored inline, see note above)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo_url', 1), ('logo_upload', 2)]], {})}),
        ),
    ]
