"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-hf(e5bhp@+w)w5650!tjsf8v!cea1beya&n45kj5mjgcl$u-dg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# Encrypts AI provider API keys at rest (ai_core.crypto) — deliberately a
# separate key from SECRET_KEY (never reuse a signing key for encryption).
# The dev default below is a real, valid Fernet key but is committed to the
# repo, so it's exactly as "insecure by design for local dev only" as
# SECRET_KEY's own default above; production sets a real one via env var.
AI_CREDENTIAL_ENCRYPTION_KEY = os.getenv(
    'AI_CREDENTIAL_ENCRYPTION_KEY',
    'ZIsGf7tB8KCrj-l1N9b3VbsycF78V6nnYPEywQlcO1Q=' if DEBUG else '',
)

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Vercel sets VERCEL_URL to the current deployment's hostname (production
# alias and preview URLs alike) — trust it automatically so we don't have to
# hardcode/update it by hand for every deployment.
VERCEL_URL = os.getenv('VERCEL_URL')
if VERCEL_URL and VERCEL_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(VERCEL_URL)

# VERCEL_URL is only this *specific* deployment's auto-generated hash
# hostname, not the stable production alias (e.g. backend-bay-three-53.
# vercel.app) — that alias is a different hostname on every new deploy's
# VERCEL_URL, so relying on VERCEL_URL alone means every redeploy has a
# real chance of 400ing every request with DisallowedHost the moment the
# alias no longer happens to match. No DJANGO_ALLOWED_HOSTS env var is set
# in production, so trust the whole *.vercel.app subdomain (every
# deployment hash and alias this project could ever have lives there) as a
# durable fallback instead of one hardcoded hostname that breaks again next
# deploy.
if '.vercel.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.vercel.app')

# The product's real custom domain (added 2026-08-24) — unlike the Vercel
# hash/alias churn above, this is a stable, deliberately-chosen hostname
# that isn't going anywhere, so it's hardcoded here rather than routed
# through the (currently unset) DJANGO_ALLOWED_HOSTS env var.
for _custom_host in ('pulsehcms.com', 'www.pulsehcms.com', 'api.pulsehcms.com'):
    if _custom_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_custom_host)

CSRF_TRUSTED_ORIGINS = [
    (f'https://*{host}' if host.startswith('.') else f'https://{host}')
    for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1')
]

# Vercel terminates TLS and proxies requests over HTTP internally, so Django
# needs this to correctly detect HTTPS (request.is_secure(), CSRF checks).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # Unfold must come before django.contrib.admin to theme it
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'core',

    # Pulse product modules — each is its own Django app so a module's data
    # model stays independent of the others (see core for shared/
    # cross-cutting concerns: auth, ActivityLog, IsOwner permission).
    'recruit',
    'payroll_benefits',
    'people',
    'talent',
    'it_assets',
    'ai_core',
    'integrations',

    # Wagtail CMS
    'cms',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.api.v2',
    'wagtail.contrib.settings',
    'wagtail',
    'modelcluster',
    'taggit',
    'wagtail_headless_preview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

CORS_ALLOWED_ORIGINS = os.getenv(
    'DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:3000'
).split(',')

# Same reasoning as the ALLOWED_HOSTS additions above: the frontend's own
# Vercel deployment hash/alias changes on every redeploy (so a fixed
# DJANGO_CORS_ALLOWED_ORIGINS env var entry for it goes stale), and the
# product's real custom domain is a stable hostname worth hardcoding rather
# than depending on the env var already holding it correctly.
CORS_ALLOWED_ORIGIN_REGEXES = [r'^https://([\w-]+\.)*vercel\.app$']
for _custom_origin in ('https://pulsehcms.com', 'https://www.pulsehcms.com', 'https://api.pulsehcms.com'):
    if _custom_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_custom_origin)

# The refresh token is set as an httpOnly cookie (see core/cookies.py), so the
# browser needs permission to send it cross-origin to this API.
CORS_ALLOW_CREDENTIALS = True

# The separately-deployed Next.js site — linked from the backend landing
# page, and used as the base for Wagtail's headless preview redirects.
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# One Pulse-owned Google Cloud OAuth client (unlike every other integration
# in integrations/catalog.py, this is a true OAuth flow — Calendar/Meet has
# no per-org static API key to paste). Each org individually authorizes
# this one app via Google's consent screen; see integrations/google_oauth.py.
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL',
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Lets users log in with either their username or their email address —
# ModelBackend stays after it as a fallback (also covers is_staff/is_superuser
# logins through the Django admin, which only ever submits a username).
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves static files directly from the WSGI app — this is what
# actually gets the Django admin, Wagtail admin, and Unfold CSS/JS working on
# Vercel, since there's no separate static-file host and `collectstatic` has
# to have already been run for STATIC_ROOT to have anything in it.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # JWT only — this API has no session-based auth to fall back to; the
    # SPA runs entirely on the bearer token + httpOnly refresh cookie
    # scheme in core/auth_views.py, and Django Admin's own session cookie
    # lives on the same domain but authenticates admin.site.urls directly,
    # never through DRF. SessionAuthentication was previously also listed
    # here (DRF's own default recommendation) but that actively broke
    # things whenever both cookies coexisted in one browser — e.g. an
    # admin with /admin/ open in one tab and the SPA in another: DRF's
    # SessionAuthentication would authenticate the *admin's* Django session
    # against SPA API calls and enforce CSRF on them, 403ing requests
    # (like /auth/refresh/) that never sent a CSRF token because they were
    # never meant to need one.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Search (?search=) and ordering (?ordering=field,-other) are safe to
    # enable globally — both backends are strict no-ops on a viewset that
    # doesn't declare search_fields/ordering_fields, so this doesn't change
    # any existing endpoint's behavior until that viewset opts in. Pagination
    # is deliberately NOT set here (see core.pagination) — it changes a list
    # endpoint's response shape from a bare array to an envelope, which would
    # break every existing frontend caller at once if flipped on globally;
    # it's applied one viewset at a time, in lockstep with the matching
    # frontend page being updated to read the new shape.
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Access token: sent in the `Authorization: Bearer <token>` header, kept
# in-memory only by the frontend (never persisted to storage, so it can't be
# read back out by an XSS payload) — short-lived since there's no way to
# revoke one early.
#
# Refresh token: the only thing that actually persists across page loads. It
# lives in an httpOnly, Secure, SameSite=None cookie (see core/cookies.py) so
# frontend JS never touches its value either, only the browser does when it
# calls /api/auth/refresh/. Rotated + blacklisted on every use so a leaked
# refresh token has a one-time-use window rather than working for its full
# lifetime.
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

AUTH_COOKIE_NAME = 'Pulse_refresh'
# Non-httpOnly companion flag: middleware/client code can check *whether* a
# session might exist (to redirect away from /login or /dashboard early)
# without ever being able to read or forge the actual refresh token.
AUTH_SESSION_FLAG_COOKIE_NAME = 'Pulse_has_session'
AUTH_COOKIE_SAMESITE = os.getenv('DJANGO_AUTH_COOKIE_SAMESITE', 'Lax' if DEBUG else 'None')
AUTH_COOKIE_SECURE = os.getenv('DJANGO_AUTH_COOKIE_SECURE', str(not DEBUG)) == 'True'

# Email (password-reset links, demo-request notifications). Defaults to
# printing messages to the console so local dev works with zero setup —
# set DJANGO_EMAIL_HOST etc. in the environment to send real mail in
# production.
if os.getenv('DJANGO_EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.getenv('DJANGO_EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@Pulse.app')
# Where "Book a Demo" form submissions get emailed for someone to follow up.
DEMO_REQUEST_NOTIFY_EMAIL = os.getenv('DEMO_REQUEST_NOTIFY_EMAIL', '')

# Wagtail
WAGTAIL_SITE_NAME = 'Pulse CMS'
WAGTAILADMIN_BASE_URL = os.getenv('WAGTAILADMIN_BASE_URL', 'http://localhost:8000')
WAGTAIL_APPEND_SLASH = False

# Headless preview: clicking "Preview" in Wagtail redirects the editor to the
# Next.js frontend's /preview route with ?content_type=...&token=..., which
# fetches the *draft* page data from api/cms/v2/page_preview/ and renders it
# with the same components the real page uses.
WAGTAIL_HEADLESS_PREVIEW = {
    'CLIENT_URLS': {
        'default': f'{FRONTEND_URL}/preview',
    },
    'REDIRECT_ON_PREVIEW': True,
    'ENFORCE_TRAILING_SLASH': False,
}

# Unfold (theming django.contrib.admin, kept separate from the Wagtail CMS admin at /cms/)
UNFOLD = {
    'SITE_TITLE': 'Pulse Admin',
    'SITE_HEADER': 'Pulse',
    'SITE_SYMBOL': 'business_center',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'COLORS': {
        'primary': {
            '50': '236 253 245',
            '100': '209 250 229',
            '200': '167 243 208',
            '300': '110 231 183',
            '400': '52 211 153',
            '500': '20 107 76',
            '600': '11 61 46',
            '700': '11 61 46',
            '800': '6 46 35',
            '900': '4 33 25',
            '950': '2 20 15',
        },
    },
}
