# Generated by Django 5.2.16 on 2026-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_recruiterfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, help_text='Google Meet, Udemy Business, LinkedIn Learning, or any other course URL.'),
        ),
        migrations.AddField(
            model_name='goal',
            name='section',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
