# Generated by Django 5.2.16 on 2026-07-24 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applied_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='posted_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
