# Generated by Django 5.2.16 on 2026-08-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_key', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('webhook', 'Custom Webhook'), ('twilio', 'Twilio (SMS)')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('encrypted_config', models.BinaryField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'integration_key'), name='one_connection_per_owner_per_integration')],
            },
        ),
    ]
