# Generated by Django 5.2.16 on 2026-08-25 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='integration_key',
            field=models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('webhook', 'Custom Webhook'), ('twilio', 'Twilio (SMS)'), ('smtp', 'Email (SMTP)'), ('wise', 'Wise'), ('deel', 'Deel'), ('remote', 'Remote'), ('hackerrank', 'HackerRank'), ('zoom', 'Zoom'), ('checkr', 'Checkr'), ('dropbox_sign', 'Dropbox Sign')], max_length=30),
        ),
        migrations.CreateModel(
            name='GoogleOAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('encrypted_access_token', models.BinaryField()),
                ('encrypted_refresh_token', models.BinaryField()),
                ('token_expires_at', models.DateTimeField()),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
