# Generated by Django 5.2.16 on 2026-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationconnection_integration_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='integration_key',
            field=models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('webhook', 'Custom Webhook'), ('zapier', 'Zapier'), ('twilio', 'Twilio (SMS)'), ('smtp', 'Email (SMTP)'), ('wise', 'Wise'), ('deel', 'Deel'), ('remote', 'Remote'), ('hackerrank', 'HackerRank'), ('zoom', 'Zoom'), ('checkr', 'Checkr'), ('dropbox_sign', 'Dropbox Sign'), ('surveymonkey', 'SurveyMonkey')], max_length=30),
        ),
    ]
