# Generated by Django 5.2.16 on 2026-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_employee_portal_token_attendancerecord_leaverequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
