# Generated by Django 5.2.16 on 2026-08-08 15:28
# Manually reordered + a data migration inserted so existing Survey rows'
# single `question` value survives the switch to a `questions` list,
# instead of being silently dropped by a straight remove+add.

from django.db import migrations, models


def copy_question_into_questions(apps, schema_editor):
    Survey = apps.get_model('people', 'Survey')
    for survey in Survey.objects.exclude(question=''):
        survey.questions = [survey.question]
        survey.save(update_fields=['questions'])


def copy_questions_into_question(apps, schema_editor):
    Survey = apps.get_model('people', 'Survey')
    for survey in Survey.objects.all():
        survey.question = survey.questions[0] if survey.questions else ''
        survey.save(update_fields=['question'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_employee_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.JSONField(default=list, help_text='The question(s) employees are asked to respond to.'),
        ),
        migrations.RunPython(copy_question_into_questions, copy_questions_into_question),
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.AddField(
            model_name='employee',
            name='client_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Salaried', 'Salaried'), ('Contract', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='recognition_type',
            field=models.CharField(choices=[('Employee of the Month', 'Employee of the Month'), ('Work Anniversary', 'Work Anniversary'), ('Above & Beyond', 'Above & Beyond'), ('Team Player', 'Team Player'), ('Innovation Award', 'Innovation Award'), ('Milestone Achievement', 'Milestone Achievement')], default='Above & Beyond', max_length=30),
        ),
        migrations.AddField(
            model_name='survey',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Bi-yearly', 'Bi-yearly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
