# Generated by Django 5.2.16 on 2026-07-25 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Plain-text resume content, used for AI screening keyword matching.'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('Criminal', 'Criminal'), ('Employment', 'Employment history'), ('Education', 'Education'), ('Credit', 'Credit'), ('Reference', 'Reference')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Cleared', 'Cleared'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='recruit.candidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('rehire_eligible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not started'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to='recruit.candidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Documents Checklist', 'Documents checklist'), ('Access Status', 'Access status'), ('Hardware Clearance', 'Hardware clearance')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='recruit.offboarding')),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('body', models.TextField(help_text='The offer letter content itself.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Signed', 'Signed'), ('Declined', 'Declined')], default='Draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='recruit.candidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Not Started', 'Not started'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='recruit.candidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pre-Joining Documents', 'Pre-Joining documents'), ('Orientation', 'Orientation'), ('Training Plan', 'Training plan and schedule'), ('Portal Access', 'Portal access and installations'), ('Probation Evaluation', 'Probation evaluation'), ('Device Assignment', 'Device assignment')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='recruit.onboarding')),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
