# Generated by Django 5.2.16 on 2026-07-26 09:56

import uuid
from django.db import migrations, models


def populate_portal_tokens(apps, schema_editor):
    # A plain AddField with unique=True bakes a single computed default into
    # the ALTER TABLE's SQL DEFAULT clause — every existing row gets the
    # *same* UUID, which immediately violates the unique constraint. Add the
    # column nullable first, backfill a fresh uuid4 per row here, then
    # tighten it to unique+non-null in a separate AlterField.
    Candidate = apps.get_model('recruit', 'Candidate')
    for candidate in Candidate.objects.all():
        candidate.portal_token = uuid.uuid4()
        candidate.save(update_fields=['portal_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_candidate_ai_score_candidate_ai_score_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='portal_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_portal_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidate',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='offboarding',
            name='rehire_notes',
            field=models.TextField(blank=True),
        ),
    ]
