# Generated by Django 5.2.16 on 2026-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_candidate_portal_token_offboarding_rehire_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundcheck',
            name='check_type',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Criminal', 'Criminal'), ('EEC', 'Education + Employment + Criminal (EEC)')], max_length=20),
        ),
    ]
