# Generated by Django 5.2.16 on 2026-08-15 06:53

from django.db import migrations, models


def rename_pre_joining_category(apps, schema_editor):
    OnboardingTask = apps.get_model('recruit', 'OnboardingTask')
    OnboardingTask.objects.filter(category='Pre-Joining Documents').update(category='Joining Documentation')


def revert_pre_joining_category(apps, schema_editor):
    OnboardingTask = apps.get_model('recruit', 'OnboardingTask')
    OnboardingTask.objects.filter(category='Joining Documentation').update(category='Pre-Joining Documents')


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_candidate_current_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='offboardingtask',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='offboarding-documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='offboardingtask',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='onboarding-documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requisition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='headcount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisition',
            name='hiring_manager',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='requisition',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='requisition',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='category',
            field=models.CharField(choices=[('Joining Documentation', 'Joining documentation'), ('Orientation', 'Orientation'), ('Training Plan', 'Training plan and schedule'), ('Portal Access', 'Portal access and installations'), ('Probation Evaluation', 'Probation evaluation'), ('Device Assignment', 'Device assignment')], max_length=30),
        ),
        migrations.RunPython(rename_pre_joining_category, revert_pre_joining_category),
    ]
