# Generated by Django 5.2.16 on 2026-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_candidate_city_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_score_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
