# Generated by Django 5.2.16 on 2026-08-15 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_candidate_ai_score_gaps_candidate_ai_score_strengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offboarding',
            name='rehire_interest',
            field=models.CharField(choices=[('Not Contacted', 'Not contacted'), ('Interested', 'Interested'), ('Not Interested', 'Not interested'), ('Rehired', 'Rehired')], default='Not Contacted', max_length=20),
        ),
        migrations.AddField(
            model_name='offboarding',
            name='rehire_last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='The offer letter template content — used to pre-fill a new offer for this role.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_templates', to='recruit.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__name', 'role_title'],
            },
        ),
    ]
