# Generated by Django 5.2.16 on 2026-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_offboarding_rehire_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheck',
            name='checkr_candidate_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='checkr_report_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='dropbox_sign_request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
