# Generated by Django 5.2.16 on 2026-08-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_backgroundcheck_checkr_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hackerrank_candidate_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hackerrank_report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hackerrank_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hackerrank_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hackerrank_test_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
