# Generated by Django 5.2.16 on 2026-08-15 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('openai_compatible', 'Other (OpenAI-compatible)')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('base_url', models.URLField(blank=True)),
                ('model', models.CharField(max_length=100)),
                ('encrypted_api_key', models.BinaryField()),
                ('key_last4', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('resume_screening', 'AI Resume Screening')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feature_overrides', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_overrides', to='ai_core.aiprovidercredential')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aiprovidercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='one_default_ai_credential_per_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='aifeatureoverride',
            unique_together={('owner', 'feature_key')},
        ),
    ]
