# Generated by Django 5.2.16 on 2026-08-11 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_assets', '0001_initial'),
        ('people', '0004_remove_survey_question_employee_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_document',
            field=models.FileField(blank=True, null=True, upload_to='warranty-documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assetincident',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='AssetRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Recovered', 'Recovered'), ('Not Returned', 'Not Returned')], default='Pending', max_length=20)),
                ('recovered_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='it_assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_recoveries', to='people.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset recoveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
