# Generated by Django 5.2.16 on 2026-07-26 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_benefits', '0001_initial'),
        ('people', '0002_employee_portal_token_attendancerecord_leaverequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='audit_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='discrepancy_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default='Checking', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='people.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plan_type', models.CharField(choices=[('Health', 'Health'), ('Dental', 'Dental'), ('Vision', 'Vision'), ('Retirement', 'Retirement'), ('Life Insurance', 'Life Insurance'), ('Other', 'Other')], default='Health', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('employee_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_level', models.CharField(choices=[('Employee Only', 'Employee Only'), ('Employee + Spouse', 'Employee + Spouse'), ('Employee + Children', 'Employee + Children'), ('Family', 'Family')], default='Employee Only', max_length=25)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Pending', 'Pending'), ('Waived', 'Waived'), ('Terminated', 'Terminated')], default='Pending', max_length=15)),
                ('enrolled_at', models.DateField(blank=True, null=True)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='people.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='payroll_benefits.benefitplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Submitted', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_claims', to='people.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_claims', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='payroll_benefits.benefitplan')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Tax Filing', 'Tax Filing'), ('Currency Update', 'Currency Update'), ('Regulatory', 'Regulatory')], default='Tax Filing', max_length=20)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('filing_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Head of Household', 'Head of Household'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=20)),
                ('compliance_status', models.CharField(choices=[('Compliant', 'Compliant'), ('Pending Review', 'Pending Review'), ('Action Required', 'Action Required')], default='Pending Review', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to='people.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'employee__name'],
            },
        ),
    ]
