# Generated by Django 5.2.16 on 2026-08-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_benefits', '0002_payrollrun_audit_notes_payrollrun_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='linked_payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_events', to='payroll_benefits.payrollrun'),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
