# Generated by Django 5.2.16 on 2026-08-10 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_benefits', '0003_bankaccount_bank_country_complianceevent_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['currency'],
                'unique_together': {('owner', 'currency')},
            },
        ),
    ]
